### ISSUE TITLE
Can not install node-imagemagick-native on macOS

### ISSUE THREAD

**Issue by JeffreyArts** [elad/node-imagemagick-native#201]
**OS**
macOS Big Sur v11.2.3

**Imagemagick**
Version: ImageMagick 7.0.10-30 Q16 x86_64 2020-09-21

**Node**
v14.15.5

$ npm i --save node-imagemagick-native

> imagemagick-native@1.9.3 install /node_modules/imagemagick-native
> node-gyp rebuild

gyp: Call to 'sw_vers | grep 'ProductVersion:' | grep -o '10.[0-9]*'' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/.nvm/versions/node/v14.15.5/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Darwin 20.3.0
gyp ERR! command "/.nvm/versions/node/v14.15.5/bin/node" "/.nvm/versions/node/v14.15.5/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /node_modules/imagemagick-native
gyp ERR! node -v v14.15.5
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! imagemagick-native@1.9.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the imagemagick-native@1.9.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by JeffreyArts** [comment]
> pkg-config 0.29.2_3 is already installed and up-to-date.

**Comment by caraya** [comment]
The problem is that the code in binding.gyp is looking for a 10.x version of macOS `grep -o '10.[0-9]*` SInce most current versions of macOS are 11.x the build will fail. 

The comment in line 12 of [binding.gyp](https://github.com/elad/node-imagemagick-native/blob/1831117866d41b87b19fb5f93564a0ea994aff12/binding.gyp#L12) confirms the problem

All other macOS-related configurations are also hardcoded for macOS 10.x and will not work with the current version of macOS or any future version.
